ServerEvents.recipes(event => {
    
    event.recipes.gtceu.assembler('1k_cell')
        .itemInputs('2x gtceu:certus_quartz_gem','ae2:logic_processor')
        .inputFluids('gtceu:redstone 144')
        .itemOutputs('ae2:cell_component_1k')
        .duration(250)
        .EUt(GTValues.VA[GTValues.LV])
event.recipes.gtceu.assembler('4k_cell')
        .itemInputs('3x ae2:cell_component_1k','ae2:calculation_processor')
        .inputFluids('gtceu:redstone 144',)
        .itemOutputs('ae2:cell_component_4k')
        .duration(250)
        .EUt(GTValues.VA[GTValues.MV])
        event.recipes.gtceu.assembler('16k_cell')
        .itemInputs('3x ae2:cell_component_4k','ae2:calculation_processor')
        .inputFluids('gtceu:glowstone 144',)
        .itemOutputs('ae2:cell_component_16k')
        .duration(250)
        .EUt(GTValues.VA[GTValues.MV])
            event.recipes.gtceu.assembler('64k_cell')
        .itemInputs('3x ae2:cell_component_16k','ae2:calculation_processor')
        .inputFluids('gtceu:glowstone 144',)
        .itemOutputs('ae2:cell_component_64k')
        .duration(250)
        .EUt(GTValues.VA[GTValues.MV])
            event.recipes.gtceu.assembler('256k_cell')
        .itemInputs('3x ae2:cell_component_64k','ae2:calculation_processor')
        .inputFluids('gtceu:moon_stone 144')
        .itemOutputs('ae2:cell_component_256k')
        .duration(250)
        .EUt(GTValues.VA[GTValues.MV])
         event.recipes.gtceu.assembler('1m_cell')
        .itemInputs('3x ae2:cell_component_256k','megacells:accumulation_processor')
        .inputFluids('gtceu:moon_stone 144')
        .itemOutputs('megacells:cell_component_1m')
        .duration(250)
        .EUt(GTValues.VA[GTValues.EV])
            event.recipes.gtceu.assembler('4m_cell')
        .itemInputs('3x megacells:cell_component_1m','megacells:accumulation_processor')
        .inputFluids('gtceu:ender 144')
        .itemOutputs('megacells:cell_component_4m')
        .duration(250)
        .EUt(GTValues.VA[GTValues.EV])
             event.recipes.gtceu.assembler('16m_cell')
        .itemInputs('3x megacells:cell_component_4m','megacells:accumulation_processor',)
        .inputFluids('gtceu:ender 144')
        .itemOutputs('megacells:cell_component_16m')
        .duration(250)
        .EUt(GTValues.VA[GTValues.EV])
           event.recipes.gtceu.assembler('64m_cell')
        .itemInputs('3x megacells:cell_component_16m','megacells:accumulation_processor',)
        .inputFluids('gtceu:stainless_steel 144')
        .itemOutputs('megacells:cell_component_64m')
        .duration(250)
        .EUt(GTValues.VA[GTValues.EV])
           event.recipes.gtceu.assembler('256m_cell')
        .itemInputs('3x megacells:cell_component_64m','megacells:accumulation_processor',)
        .inputFluids('gtceu:stainless_steel 144')
        .itemOutputs('megacells:cell_component_256m')
        .duration(250)
        .EUt(GTValues.VA[GTValues.EV])
         event.recipes.gtceu.assembler('bulk_cell')
        .itemInputs('2x megacells:cell_component_1m','2x megacells:accumulation_processor',)
        .inputFluids('gtceu:ender 144')
        .itemOutputs('megacells:bulk_cell_component')
        .duration(250)
        .EUt(GTValues.VA[GTValues.EV])
})