ServerEvents.recipes(event => {
    event.recipes.gtceu.assembler('wireless_booster')
        .itemInputs('3x gtceu:iron_plate','gtceu:fluix_gem','gtceu:certus_quartz_gem')
        .inputFluids('gtceu:ender 144')
        .itemOutputs('4x ae2:wireless_booster')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])
        event.recipes.gtceu.assembler('controller-ae')
        .itemInputs('ae2:engineering_processor','4x gtceu:fluix_gem',)
        .inputFluids('gtceu:moon_stone 144')
        .itemOutputs('ae2:controller')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
         event.recipes.gtceu.assembler('wireless_access_point')
        .itemInputs('ae2:wireless_receiver','ae2:fluix_glass_cable','ae2:calculation_processor')
        .itemOutputs('ae2:wireless_access_point')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])
        event.recipes.gtceu.assembler('drive-ae')
        .itemInputs('2x ae2:fluix_glass_cable','ae2:engineering_processor','4x gtceu:iron_plate')
        .itemOutputs('ae2:drive')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
         event.recipes.gtceu.assembler('endergy_cell-ae')
        .itemInputs('4x gtceu:fluix_dust','4x gtceu:certus_quartz_gem',)
        .inputFluids('gtceu:glass 144')
        .itemOutputs('ae2:energy_cell')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
         event.recipes.gtceu.assembler('assembler-ae')
        .itemInputs('4x gtceu:iron_plate','4x gtceu:fluix_gem',)
        .inputFluids('gtceu:charged_certus_solution 144')
        .itemOutputs('ae2:molecular_assembler')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])
         event.recipes.gtceu.assembler('pattern-ae')
        .itemInputs('2x minecraft:crafting_table','4x gtceu:fluix_gem','4x gtceu:iron_plate')
        .inputFluids('gtceu:charged_certus_solution 144')
        .itemOutputs('ae2:pattern_provider')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
           event.recipes.gtceu.assembler('quartz-cable-ae')
        .itemInputs('3x gtceu:certus_quartz_dust','gtceu:nether_quartz_dust')
        .inputFluids('gtceu:glass 144')
        .itemOutputs('4x ae2:quartz_fiber')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
            event.recipes.gtceu.assembler('fluix-cable-ae')
        .itemInputs('ae2:quartz_fiber')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('4x ae2:fluix_glass_cable')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
          event.recipes.gtceu.assembler('import-bus-ae')
        .itemInputs('2x gtceu:iron_plate','gtceu:sticky_resin','gtceu:wood_plate')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('2x ae2:import_bus')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
        event.recipes.gtceu.assembler('export-bus-ae')
        .itemInputs('2x gtceu:iron_plate','gtceu:wood_plate')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('2x ae2:export_bus')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
         event.recipes.gtceu.assembler('illuminated-pane-ae')
        .itemInputs('2x gtceu:iron_plate','2x minecraft:glowstone_dust','minecraft:redstone')
        .inputFluids('gtceu:glass 144')
        .itemOutputs('4x ae2:semi_dark_monitor')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
        event.recipes.gtceu.assembler('terminal--ae')
        .itemInputs('2x gtceu:iron_plate','ae2:semi_dark_monitor','ae2:logic_processor')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('ae2:terminal')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
         event.recipes.gtceu.assembler('terminal-encode-ae')
        .itemInputs('ae2:terminal','ae2:engineering_processor')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('ae2:pattern_encoding_terminal')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
             event.recipes.gtceu.assembler('terminal-craft-ae')
        .itemInputs('ae2:terminal','ae2:calculation_processor','minecraft:crafting_table')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('ae2:crafting_terminal')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
         event.recipes.gtceu.assembler('terminal-access-ae')
        .itemInputs('ae2:terminal','ae2:calculation_processor','ae2:pattern_provider')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('ae2:pattern_access_terminal')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
         event.recipes.gtceu.assembler('wireless-block-ae')
        .itemInputs('3x #ae2:smart_cable','3x ae2:calculation_processor','gtceu:wireless_transmitter_cover')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('expatternprovider:wireless_hub')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])
           event.recipes.gtceu.assembler('wireless-terminal-ae')
        .itemInputs('ae2:dense_energy_cell','ae2:terminal','ae2:wireless_receiver')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('ae2:wireless_terminal')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])
        event.recipes.gtceu.assembler('wireless-craft-terminal-ae')
        .itemInputs('minecraft:crafting_table','ae2:wireless_terminal')
        .inputFluids('gtceu:fluix 144')
        .itemOutputs('ae2:wireless_crafting_terminal')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])
        event.recipes.gtceu.assembler("blank_pattern")
        .itemInputs("3x gtceu:iron_plate")
        .itemInputs("3x minecraft:glowstone_dust")
        .itemInputs("gtceu:certus_quartz_gem")
        .itemOutputs("6x ae2:blank_pattern")
        .inputFluids("gtceu:glass 144")
        .EUt(480)
        .duration(200)
        event.recipes.gtceu.assembler("interface")
.itemInputs("3x gtceu:iron_plate")
.itemInputs("3x gtceu:fluix_gem")
.itemInputs("3x gtceu:certus_quartz_gem")
.itemOutputs("ae2:interface")
.inputFluids("gtceu:glass 144")
.EUt(100)
.duration(100)
event.recipes.gtceu.assembler("dense_energy_cell")
.itemInputs("6x ae2:energy_cell")
.itemInputs("ae2:calculation_processor")
.itemOutputs("ae2:dense_energy_cell")
.inputFluids("gtceu:fluix 144")
.EUt(480)
.duration(100)
event.recipes.gtceu.assembler("crafting_unit")
.itemInputs("ae2:fluix_glass_cable")
.itemInputs("4x gtceu:iron_plate")
.itemInputs("ae2:logic_processor")
.itemInputs("ae2:calculation_processor")
.itemInputs("ae2:engineering_processor")
.itemOutputs("ae2:crafting_unit")
.EUt(400)
.duration(500)
event.recipes.gtceu.assembler("crafting_accelerator")
.itemInputs("ae2:crafting_unit")
.itemInputs("ae2:engineering_processor")
.itemOutputs("ae2:crafting_accelerator")
.circuit(1)
.EUt(400)
.duration(500)
event.recipes.gtceu.assembler("level_emitter")
.itemInputs("minecraft:redstone_torch")
.itemInputs("ae2:calculation_processor")
.itemOutputs("ae2:level_emitter")
.circuit(1)
.EUt(300)
.duration(200)
event.recipes.gtceu.assembler("storage_monitor")
.itemInputs("ae2:level_emitter")
.itemInputs("#ae2:illuminated_panel")
.itemOutputs("ae2:storage_monitor")
.circuit(1)
.EUt(300)
.duration(200)
event.recipes.gtceu.assembler("crafting_monitor")
.itemInputs("ae2:storage_monitor")
.itemInputs("ae2:crafting_unit")
.itemOutputs("ae2:crafting_monitor")
.circuit(1)
.EUt(300)
.duration(200)
event.recipes.gtceu.assembler("p2p")
.itemInputs("3x gtceu:iron_plate")
.itemInputs("ae2:engineering_processor")
.itemOutputs("ae2:me_p2p_tunnel")
.inputFluids("gtceu:fluix 144")
.circuit(2)
.EUt(200)
.duration(120)
event.recipes.gtceu.assembler("infrange")
.itemInputs("gtceu:nether_star_dust")
.itemInputs("3x gtceu:platinum_plate")
.itemInputs("3x ae2:wireless_booster")
.itemOutputs("aeinfinitybooster:infinity_card")
.inputFluids("gtceu:ender 144")
.EUt(480)
.duration(3000)




        
       

       })
